require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SupermercadosController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Supermercado. As you add validations to Supermercado, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SupermercadosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all supermercados as @supermercados" do
      supermercado = Supermercado.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:supermercados)).to eq([supermercado])
    end
  end

  describe "GET show" do
    it "assigns the requested supermercado as @supermercado" do
      supermercado = Supermercado.create! valid_attributes
      get :show, {:id => supermercado.to_param}, valid_session
      expect(assigns(:supermercado)).to eq(supermercado)
    end
  end

  describe "GET new" do
    it "assigns a new supermercado as @supermercado" do
      get :new, {}, valid_session
      expect(assigns(:supermercado)).to be_a_new(Supermercado)
    end
  end

  describe "GET edit" do
    it "assigns the requested supermercado as @supermercado" do
      supermercado = Supermercado.create! valid_attributes
      get :edit, {:id => supermercado.to_param}, valid_session
      expect(assigns(:supermercado)).to eq(supermercado)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Supermercado" do
        expect {
          post :create, {:supermercado => valid_attributes}, valid_session
        }.to change(Supermercado, :count).by(1)
      end

      it "assigns a newly created supermercado as @supermercado" do
        post :create, {:supermercado => valid_attributes}, valid_session
        expect(assigns(:supermercado)).to be_a(Supermercado)
        expect(assigns(:supermercado)).to be_persisted
      end

      it "redirects to the created supermercado" do
        post :create, {:supermercado => valid_attributes}, valid_session
        expect(response).to redirect_to(Supermercado.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved supermercado as @supermercado" do
        post :create, {:supermercado => invalid_attributes}, valid_session
        expect(assigns(:supermercado)).to be_a_new(Supermercado)
      end

      it "re-renders the 'new' template" do
        post :create, {:supermercado => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested supermercado" do
        supermercado = Supermercado.create! valid_attributes
        put :update, {:id => supermercado.to_param, :supermercado => new_attributes}, valid_session
        supermercado.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested supermercado as @supermercado" do
        supermercado = Supermercado.create! valid_attributes
        put :update, {:id => supermercado.to_param, :supermercado => valid_attributes}, valid_session
        expect(assigns(:supermercado)).to eq(supermercado)
      end

      it "redirects to the supermercado" do
        supermercado = Supermercado.create! valid_attributes
        put :update, {:id => supermercado.to_param, :supermercado => valid_attributes}, valid_session
        expect(response).to redirect_to(supermercado)
      end
    end

    describe "with invalid params" do
      it "assigns the supermercado as @supermercado" do
        supermercado = Supermercado.create! valid_attributes
        put :update, {:id => supermercado.to_param, :supermercado => invalid_attributes}, valid_session
        expect(assigns(:supermercado)).to eq(supermercado)
      end

      it "re-renders the 'edit' template" do
        supermercado = Supermercado.create! valid_attributes
        put :update, {:id => supermercado.to_param, :supermercado => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested supermercado" do
      supermercado = Supermercado.create! valid_attributes
      expect {
        delete :destroy, {:id => supermercado.to_param}, valid_session
      }.to change(Supermercado, :count).by(-1)
    end

    it "redirects to the supermercados list" do
      supermercado = Supermercado.create! valid_attributes
      delete :destroy, {:id => supermercado.to_param}, valid_session
      expect(response).to redirect_to(supermercados_url)
    end
  end

end
